require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ReviewersController do

  # This should return the minimal set of attributes required to create a valid
  # Reviewer. As you add validations to Reviewer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "user_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ReviewersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all reviewers as @reviewers" do
      reviewer = Reviewer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:reviewers).should eq([reviewer])
    end
  end

  describe "GET show" do
    it "assigns the requested reviewer as @reviewer" do
      reviewer = Reviewer.create! valid_attributes
      get :show, {:id => reviewer.to_param}, valid_session
      assigns(:reviewer).should eq(reviewer)
    end
  end

  describe "GET new" do
    it "assigns a new reviewer as @reviewer" do
      get :new, {}, valid_session
      assigns(:reviewer).should be_a_new(Reviewer)
    end
  end

  describe "GET edit" do
    it "assigns the requested reviewer as @reviewer" do
      reviewer = Reviewer.create! valid_attributes
      get :edit, {:id => reviewer.to_param}, valid_session
      assigns(:reviewer).should eq(reviewer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Reviewer" do
        expect {
          post :create, {:reviewer => valid_attributes}, valid_session
        }.to change(Reviewer, :count).by(1)
      end

      it "assigns a newly created reviewer as @reviewer" do
        post :create, {:reviewer => valid_attributes}, valid_session
        assigns(:reviewer).should be_a(Reviewer)
        assigns(:reviewer).should be_persisted
      end

      it "redirects to the created reviewer" do
        post :create, {:reviewer => valid_attributes}, valid_session
        response.should redirect_to(Reviewer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved reviewer as @reviewer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Reviewer.any_instance.stub(:save).and_return(false)
        post :create, {:reviewer => { "user_id" => "invalid value" }}, valid_session
        assigns(:reviewer).should be_a_new(Reviewer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Reviewer.any_instance.stub(:save).and_return(false)
        post :create, {:reviewer => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested reviewer" do
        reviewer = Reviewer.create! valid_attributes
        # Assuming there are no other reviewers in the database, this
        # specifies that the Reviewer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Reviewer.any_instance.should_receive(:update_attributes).with({ "user_id" => "1" })
        put :update, {:id => reviewer.to_param, :reviewer => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested reviewer as @reviewer" do
        reviewer = Reviewer.create! valid_attributes
        put :update, {:id => reviewer.to_param, :reviewer => valid_attributes}, valid_session
        assigns(:reviewer).should eq(reviewer)
      end

      it "redirects to the reviewer" do
        reviewer = Reviewer.create! valid_attributes
        put :update, {:id => reviewer.to_param, :reviewer => valid_attributes}, valid_session
        response.should redirect_to(reviewer)
      end
    end

    describe "with invalid params" do
      it "assigns the reviewer as @reviewer" do
        reviewer = Reviewer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Reviewer.any_instance.stub(:save).and_return(false)
        put :update, {:id => reviewer.to_param, :reviewer => { "user_id" => "invalid value" }}, valid_session
        assigns(:reviewer).should eq(reviewer)
      end

      it "re-renders the 'edit' template" do
        reviewer = Reviewer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Reviewer.any_instance.stub(:save).and_return(false)
        put :update, {:id => reviewer.to_param, :reviewer => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested reviewer" do
      reviewer = Reviewer.create! valid_attributes
      expect {
        delete :destroy, {:id => reviewer.to_param}, valid_session
      }.to change(Reviewer, :count).by(-1)
    end

    it "redirects to the reviewers list" do
      reviewer = Reviewer.create! valid_attributes
      delete :destroy, {:id => reviewer.to_param}, valid_session
      response.should redirect_to(reviewers_url)
    end
  end

end
