require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SealsController do

  # This should return the minimal set of attributes required to create a valid
  # Seal. As you add validations to Seal, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "project_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SealsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all seals as @seals" do
      seal = Seal.create! valid_attributes
      get :index, {}, valid_session
      assigns(:seals).should eq([seal])
    end
  end

  describe "GET show" do
    it "assigns the requested seal as @seal" do
      seal = Seal.create! valid_attributes
      get :show, {:id => seal.to_param}, valid_session
      assigns(:seal).should eq(seal)
    end
  end

  describe "GET new" do
    it "assigns a new seal as @seal" do
      get :new, {}, valid_session
      assigns(:seal).should be_a_new(Seal)
    end
  end

  describe "GET edit" do
    it "assigns the requested seal as @seal" do
      seal = Seal.create! valid_attributes
      get :edit, {:id => seal.to_param}, valid_session
      assigns(:seal).should eq(seal)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Seal" do
        expect {
          post :create, {:seal => valid_attributes}, valid_session
        }.to change(Seal, :count).by(1)
      end

      it "assigns a newly created seal as @seal" do
        post :create, {:seal => valid_attributes}, valid_session
        assigns(:seal).should be_a(Seal)
        assigns(:seal).should be_persisted
      end

      it "redirects to the created seal" do
        post :create, {:seal => valid_attributes}, valid_session
        response.should redirect_to(Seal.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved seal as @seal" do
        # Trigger the behavior that occurs when invalid params are submitted
        Seal.any_instance.stub(:save).and_return(false)
        post :create, {:seal => { "project_id" => "invalid value" }}, valid_session
        assigns(:seal).should be_a_new(Seal)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Seal.any_instance.stub(:save).and_return(false)
        post :create, {:seal => { "project_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested seal" do
        seal = Seal.create! valid_attributes
        # Assuming there are no other seals in the database, this
        # specifies that the Seal created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Seal.any_instance.should_receive(:update_attributes).with({ "project_id" => "1" })
        put :update, {:id => seal.to_param, :seal => { "project_id" => "1" }}, valid_session
      end

      it "assigns the requested seal as @seal" do
        seal = Seal.create! valid_attributes
        put :update, {:id => seal.to_param, :seal => valid_attributes}, valid_session
        assigns(:seal).should eq(seal)
      end

      it "redirects to the seal" do
        seal = Seal.create! valid_attributes
        put :update, {:id => seal.to_param, :seal => valid_attributes}, valid_session
        response.should redirect_to(seal)
      end
    end

    describe "with invalid params" do
      it "assigns the seal as @seal" do
        seal = Seal.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Seal.any_instance.stub(:save).and_return(false)
        put :update, {:id => seal.to_param, :seal => { "project_id" => "invalid value" }}, valid_session
        assigns(:seal).should eq(seal)
      end

      it "re-renders the 'edit' template" do
        seal = Seal.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Seal.any_instance.stub(:save).and_return(false)
        put :update, {:id => seal.to_param, :seal => { "project_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested seal" do
      seal = Seal.create! valid_attributes
      expect {
        delete :destroy, {:id => seal.to_param}, valid_session
      }.to change(Seal, :count).by(-1)
    end

    it "redirects to the seals list" do
      seal = Seal.create! valid_attributes
      delete :destroy, {:id => seal.to_param}, valid_session
      response.should redirect_to(seals_url)
    end
  end

end
